name: Deploy Node Application
on:
  push:
    branches:
      - mern-ec2-docker-ssl
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t mickey761/node.
      - name: Publish Image to Docker Hub
        run: docker push mickey761/node:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull mickey761/node:latest
      - name: Delete old container (ignore error if not exists)
        run: docker rm -f node-container || true
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name node-container -e MONGO_URI="${{ secrets.MONGO_URI }}" mickey761/node:latest