name: Deploy Node Application

on:
  push:
    branches:
      - mern-ec2-docker-ssl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app .
      - name: Publish Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest



        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop existing container if running
            docker stop nodejs-app || true
            docker rm nodejs-app || true
            
            # Pull and run new container
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest
            docker run -d \
              --name nodejs-app \
              -p 4000:4000 \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest